### ISSUE TITLE
90u-2 Upgrade

### ISSUE THREAD

**Issue by discoverdefiteam** [terpnetwork/test-net#5]
We need to prepare all necessary information & resources for coordinating a fresh, public test-network, labeled `90u-2`.

**Comment by hard-nett** [comment]
Commits preparing for the new test network can be found [here.](https://github.com/hard-nett/test-net)

**Comment by hard-nett** [comment]
#6

**Comment by hard-nett** [comment]
upgrade documentation merged in #6
